sudo: false
language: java
jdk:
- openjdk8
install: ./gradlew assemble
before_script:
- sleep 15
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  apt: true
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
- openssl aes-256-cbc -K $encrypted_1c9b4450e523_key -iv $encrypted_1c9b4450e523_iv
  -in gradle.properties.enc -out gradle.properties -d
script: "./gradlew externalCiTest"