ena:
  experiment_sample_id: SRS000081
  processor_list: ENAStudyProcessor,ENAExperimentProcessor
  login_name: ${enaLoginName}
  password: ${enaPassword}
  submission:
    url: https://www-test.ebi.ac.uk/ena/submit/drop-box/submit
  file_move:
    webinFolderPath: /fire/staging/era/upload/Webin-46220
    logFilePath: /data/filemove.log
